### ISSUE TITLE
Add green color cell indicator for best metric value

### ISSUE THREAD

**Issue by doronbl** [aws-samples/fm-leaderboarder#2]
To have better visibility which models are winning on which metric, color the winning metric cells with green background (or at least set the metric value to bold)

**Comment by gilinachum** [comment]
@doronbl This is doable.
Did you noticed the columns are sortable by clicking on the header?
To note that in some metrics the best value is Max (Bert) and in some (Bart) it's Min value. So if it's a user defined metric we'll need to provide a way to note if it's min or max.

**Comment by doronbl** [comment]
@gilinachum sorting is not sufficient as my intention is to have visual cue for a model on all metrics

**Comment by gilinachum** [comment]
Solved in https://github.com/aws-samples/fm-leaderboarder/commit/57a364bd67f03fb8deaff8ebd19ab8c73cffa442
(The commit has 3 updates, but the notebook update is irrelevant, so you only need two of the files)
![image](https://github.com/aws-samples/fm-leaderboarder/assets/1893166/da2b3d20-e36c-45b0-b54b-b10613f86aee)
